In [1]:
import os
import quandl

In [6]:
quandl.ApiConfig.api_key = os.environ['QUANDL_API_KEY']
quandl.get('CME/SPU2018', start_date='2018-01-31', end_date='2018-09-05')

,Open,High,Low,Last,Change,Settle,Volume,Previous Day Open Interest
Date,,,,,,,,
2018-01-31,NaN,2850.4,2825.9,2838.4,1.1,2836.5,0.0,125.0
2018-02-01,NaN,2845.5,2826.5,2830.5,3.3,2833.2,0.0,125.0
2018-02-02,NaN,NaN,2770.2,2770.2,66.1,2767.1,0.0,125.0
2018-02-05,NaN,2773.1,2652.1,2682.1,150.9,2616.2,0.0,125.0
2018-02-06,NaN,2693.2,2596.2,2686.2,87.2,2703.4,0.0,125.0
2018-02-07,NaN,2733.4,2693.4,2699.4,26.6,2676.8,0.0,125.0
2018-02-08,NaN,2689.8,2592.8,2592.8,75.4,2601.4,0.0,125.0
2018-02-09,NaN,2620.4,2551.4,2616.4,25.2,2626.6,0.0,125.0
2018-02-12,NaN,2672.6,NaN,2672.6,36.8,2663.4,0.0,125.0
2018-02-13,NaN,2672.2,2643.4,2672.2,6.5,2669.9,0.0,125.0
2018-02-14,NaN,2708.2,2654.9,2708.2,35.8,2705.7,0.0,125.0
2018-02-15,NaN,2729.7,2699.7,2729.7,37.7,2743.4,0.0,125.0
2018-02-16,NaN,2758.4,2740.4,2745.4,2.0,2745.4,0.0,125.0
2018-02-20,NaN,2746.4,2720.4,2723.4,20.7,2724.7,0.0,128.0
2018-02-21,NaN,2756.7,2706.7,2706.7,14.8,2709.9,0.0,126.0
2018-02-22,NaN,2740.9,2704.9,2715.9,12.4,2722.3,0.0,126.0
2018-02-23,NaN,2753.3,NaN,2753.3,37.8,2760.1,0.0,125.0
2018-02-26,NaN,2792.1,NaN,2792.1,36.3,2796.4,0.0,125.0
2018-02-27,NaN,2801.4,2754.4,2754.4,36.2,2760.2,0.0,125.0
2018-02-28,NaN,2772.2,2727.2,2727.2,33.5,2726.7,0.0,125.0
2018-03-01,NaN,2740.7,2671.7,2691.7,36.7,2690.0,0.0,125.0
2018-03-02,NaN,2700.0,2661.1,2700.0,11.7,2701.7,0.0,125.0
2018-03-05,NaN,2736.2,2691.7,2729.7,28.4,2730.1,25.0,125.0
2018-03-06,NaN,2742.1,2726.1,2738.1,5.5,2735.6,10.0,150.0
2018-03-07,NaN,2740.2,2718.2,2740.2,0.7,2734.9,105.0,140.0
2018-03-08,NaN,2744.9,NaN,2736.9,16.2,2751.1,0.0,57.0
2018-03-09,NaN,2791.1,NaN,2791.1,45.1,2796.2,0.0,42.0
2018-03-12,NaN,2809.2,2793.2,2804.2,0.1,2796.3,0.0,40.0
2018-03-13,NaN,NaN,NaN,NaN,16.7,2779.6,15.0,40.0
2018-03-14,NaN,NaN,NaN,NaN,18.9,2760.7,0.0,25.0
...,...,...,...,...,...,...,...,...
2018-07-25,2816.0,2849.0,2814.5,2841.5,20.3,2841.3,2215.0,62742.0
2018-07-26,2836.8,2846.0,2833.7,2842.5,1.2,2842.5,2020.0,62726.0
2018-07-27,2844.8,2846.7,2809.5,2817.0,25.0,2817.5,1353.0,63250.0
2018-07-30,2810.6,2821.5,2799.0,2803.0,14.3,2803.2,1648.0,62372.0
2018-07-31,2803.7,2827.4,2803.3,2824.0,13.9,2817.1,662.0,62612.0
2018-08-01,2814.3,2825.6,2805.5,2810.5,6.3,2810.8,1223.0,62433.0
2018-08-02,2813.8,2830.7,2791.3,2828.5,17.6,2828.4,1411.0,62058.0
2018-08-03,2830.3,2840.8,2825.1,2839.2,11.1,2839.5,710.0,62389.0
2018-08-06,2842.2,2852.3,2835.5,2850.1,10.6,2850.1,1123.0,63576.0
2018-08-07,2851.5,2863.0,2848.5,2860.0,9.6,2859.7,1282.0,64489.0
2018-08-08,2860.8,2862.0,2853.0,2856.0,4.4,2855.3,1347.0,64620.0
2018-08-09,2855.3,2862.5,2851.0,2854.0,1.5,2853.8,942.0,65006.0
2018-08-10,2847.0,2847.0,2826.5,2836.5,17.0,2836.8,1595.0,64776.0
2018-08-13,2830.4,2843.5,2820.5,2825.3,11.3,2825.5,1129.0,64433.0
2018-08-14,2828.6,2843.5,2827.0,2841.0,15.5,2841.0,1053.0,64885.0
2018-08-15,2841.7,2842.5,2804.0,2821.0,19.8,2821.2,1461.0,64617.0
2018-08-16,2818.0,2851.5,2817.7,2844.2,23.5,2844.7,2119.0,65072.0
2018-08-17,2840.8,2856.6,2835.2,2852.5,7.5,2852.2,1215.0,65455.0
2018-08-20,2851.7,2861.0,2850.8,2858.8,6.4,2858.6,1721.0,65203.0
2018-08-21,2858.0,2873.5,2852.5,2861.5,3.1,2861.7,788.0,66239.0
2018-08-22,2853.4,2868.2,2846.5,2861.0,0.5,2861.2,1841.0,66171.0
2018-08-23,2864.0,2869.0,2855.5,2858.0,3.2,2858.0,1827.0,67613.0
2018-08-24,2857.8,2877.0,2856.7,2876.5,18.7,2876.7,898.0,67740.0
2018-08-27,2881.0,2899.0,2880.5,2898.7,21.7,2898.4,2402.0,68561.0
2018-08-28,2901.0,2906.0,2894.5,2899.3,0.9,2899.3,1169.0,69961.0
2018-08-29,2901.7,2917.3,2898.0,2914.5,15.4,2914.7,2732.0,70509.0
2018-08-30,2916.0,2916.0,2895.5,2901.5,12.7,2902.0,1590.0,71106.0
2018-08-31,2900.1,2907.0,2892.0,2905.5,0.1,2902.1,2586.0,70098.0
2018-09-04,2906.8,2912.3,2885.8,2898.5,3.8,2898.3,1289.0,69290.0
2018-09-05,2896.3,2900.2,2878.0,2888.5,10.0,2888.3,2670.0,69458.0

In [7]:
quandl.bulkdownload('CME')

'./CME.zip'

In [8]:
!ls

CME.zip                futures.py             run_strat.ipynb
Get Futures Data.ipynb futures.py~            strat.py
Untitled.ipynb         install_zipline.sh     strat_cf.py
__init__.py            install_zipline.sh~    strat_cf.py~
__pycache__            outfile.pickle         zipline_conda.yml
extension.py           requirements_blaze.txt zipline_conda.yml~

In [9]:
import pandas as pd

In [13]:
df = pd.read_csv('/Users/jonathan/.zipline/meta.csv')

In [17]:
df.symbol.str.len().value_counts()

12    40249
7     31149
11    30727
13    26900
10    26101
8      5320
9      2192
6      1739
14      164
Name: symbol, dtype: int64

In [18]:
df.symbol

0              0DF2015
1              0DF2016
2              0DF2017
3              0DF2018
4              0DF2019
5              0DF2020
6              0DF2021
7              0DG2014
8              0DG2015
9              0DG2016
10             0DG2017
11             0DG2018
12             0DG2019
13             0DG2020
14             0DG2021
15             0DH2014
16             0DH2015
17             0DH2016
18             0DH2017
19             0DH2018
20             0DH2019
21             0DH2020
22             0DH2021
23             0DJ2014
24             0DJ2015
25             0DJ2016
26             0DJ2017
27             0DJ2018
28             0DJ2019
29             0DJ2020
              ...
164511    ZRG2017C4_25
164512    ZRG2017C5_25
164513    ZRG2018C3_75
164514     ZRG2018C3_9
164515       ZRG2018C4
164516    ZRG2018C4_25
164517     ZRG2018C4_5
164518     ZRZ2016C3_5
164519    ZRZ2016C3_75
164520     ZRZ2016C3_9
164521       ZRZ2016C4
164522    ZRZ2016C4_25
164523    ZRZ2016C5_25
164524    ZRZ2017C3_75
164525     ZRZ2017C3_9
164526       ZRZ2017C4
164527    ZRZ2017C4_25
164528     ZRZ2017C4_5
164529          ZU2014
164530          ZU2015
164531          ZU2016
164532          ZU2017
164533          ZU2018
164534          ZU2019
164535          ZZ2014
164536          ZZ2015
164537          ZZ2016
164538          ZZ2017
164539          ZZ2018
164540          ZZ2019
Name: symbol, Length: 164541, dtype: object